server:
    port: 8080

spring:
    profiles:
        active: prod
    
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: 
        databaseName: esdemo
        serverName: localhost
        username: esdemo
        password: 

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: com.armandorv.esdemo.config.hazelcast.HazelcastCacheRegionFactory
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: esdemo

cache:
    timeToLiveSeconds: 3600
    hazelcast:
        debug: false
        stickySession: false
        backupCount: 1
